// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuor1Uf-YvPSaRtieqeuMjTYtbs2mwS1E',
    appId: '1:514221203325:web:0c64f66a6dabc049197614',
    messagingSenderId: '514221203325',
    projectId: 'skillbox-firebase-6c6e9',
    authDomain: 'skillbox-firebase-6c6e9.firebaseapp.com',
    storageBucket: 'skillbox-firebase-6c6e9.appspot.com',
    measurementId: 'G-S3YKTCML01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANfUkgzveuCrToZgzokRPhPfiKtcT86OQ',
    appId: '1:514221203325:android:a9db48df3e180a4b197614',
    messagingSenderId: '514221203325',
    projectId: 'skillbox-firebase-6c6e9',
    storageBucket: 'skillbox-firebase-6c6e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8bzIAPOAJRM5kf7Uj51KTKX3dfUwsnjE',
    appId: '1:514221203325:ios:6d2a13d79e67b7f9197614',
    messagingSenderId: '514221203325',
    projectId: 'skillbox-firebase-6c6e9',
    storageBucket: 'skillbox-firebase-6c6e9.appspot.com',
    iosClientId: '514221203325-4ef73eeg34bajv974if68us5vk546si0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8bzIAPOAJRM5kf7Uj51KTKX3dfUwsnjE',
    appId: '1:514221203325:ios:6d2a13d79e67b7f9197614',
    messagingSenderId: '514221203325',
    projectId: 'skillbox-firebase-6c6e9',
    storageBucket: 'skillbox-firebase-6c6e9.appspot.com',
    iosClientId: '514221203325-4ef73eeg34bajv974if68us5vk546si0.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseApp',
  );
}
